export default {
  NODE_ENV: process.env.NODE_ENV ?? 'production',
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID ?? '',
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY ?? '',
  AWS_S3_BUCKET: process.env.AWS_S3_BUCKET ?? 'rfcx-device-assets-staging',
  AWS_REGION_ID: process.env.AWS_REGION_ID ?? 'eu-west-1',
  AUTH0_DOMAIN: process.env.AUTH0_DOMAIN ?? 'auth.rfcx.org',
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID ?? '',
  AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET ?? '',
  AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE ?? 'https://rfcx.org',
  AUTH0_GRANT_TYPE: process.env.AUTH0_GRANT_TYPE ?? 'client_credentials',
  CORE_URL: process.env.CORE_URL ?? 'https://staging-api.rfcx.org',
  NONCORE_URL: process.env.NONCORE_URL ?? 'https://staging-api.rfcx.org',
  INGEST_SERVICE_URL: process.env.INGEST_SERVICE_URL ?? 'https://staging-ingest.rfcx.org',
  DB_HOSTNAME: process.env.DB_HOSTNAME ?? 'localhost',
  DB_PORT: process.env.DB_PORT !== undefined ? parseInt(process.env.DB_PORT) : 5432,
  DB_SSL_ENABLED: process.env.DB_SSL_ENABLED === 'true',
  DB_DEVICE_NAME: process.env.DB_DEVICE_NAME ?? 'device',
  DB_GUARDIAN_NAME: process.env.DB_GUARDIAN_NAME ?? 'guardian',
  DB_USER: process.env.DB_USER ?? 'postgres',
  DB_PASSWORD: process.env.DB_PASSWORD ?? 'test',
  MANDRILL_KEY: process.env.MANDRILL_KEY ?? '',
  CACHE_DIRECTORY: process.env.CACHE_DIRECTORY ?? './tmp',
  FFMPEG_PATH: process.env.FFMPEG_PATH ?? '/usr/local/bin/ffmpeg',
  SOX_PATH: process.env.SOX_PATH ?? '/usr/local/bin/sox',
  MQTT_BROKER_HOST: process.env.MQTT_BROKER_HOST ?? 'api-mqtt.rfcx.org',
  MQTT_BROKER_PORT: process.env.MQTT_BROKER_PORT !== undefined ? parseInt(process.env.MQTT_BROKER_PORT) : 8883,
  MQTT_BROKER_USER: process.env.MQTT_BROKER_USER ?? '',
  MQTT_BROKER_PASSWORD: process.env.MQTT_BROKER_PASSWORD ?? ''
}
