name: 'EKS-CD'
on:
  workflow_dispatch:
  push:
    branches:
      - eks-branch

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:

  configure:
      name: 'Configure'
      runs-on: ubuntu-latest
      env:
       BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      outputs:
       namespace: ${{ steps.configuration.outputs.namespace }}
       environment: ${{ steps.configuration.outputs.environment }}
      steps:
       - name: 'Conditional environment'
         id: configuration
         run: |
            echo "::set-output name=namespace::eks-test-ns"
            if [[ "$BRANCH_NAME" == "master" ]]; then
              echo "::set-output name=environment::production"
            elif [[ "$BRANCH_NAME" == "eks-branch" ]]; then
              echo "::set-output name=environment::staging"
            else
             echo "::set-output name=environment::testing"
            fi

  build:
    name: 'Build'
    needs: [configure]
    uses: rfcx/device-api/.github/workflows/eks-ecr-build-push.yaml@eks-branch
    with:
      dockerfile: build/Dockerfile
      targets: "[\"device-api\"]"
      tag-environment: ${{ needs.configure.outputs.namespace }}
      tag-latest: ${{ needs.configure.outputs.namespace == 'eks-test-ns' }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD_APP_DEPLOY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD_APP_DEPLOY }}

  deploy-device-api-secrets:
    name: 'Deploy device-api secrets'
    needs: [configure]
    uses: rfcx/cicd/.github/workflows/eks-reusable-k8s-deploy-sec.yaml@eks_cicd
    with:
      namespace: ${{ needs.configure.outputs.namespace }}
      environment: ${{ needs.configure.outputs.environment }}
      secrets_name: device-api-secrets
      secrets_list: "AWS_ACCESS_KEY_ID,AWS_SECRET_KEY,AWS_S3_BUCKET,DB_DBNAME,DB_HOSTNAME,DB_PASSWORD,DB_PORT,DB_SSL_ENABLED,DB_USER,MANDRILL_KEY"
    secrets: inherit

  deploy:
    name: 'Deploy'
    needs: [build, configure]
    uses: rfcx/device-api/.github/workflows/eks-reusable-k8s-deploy.yaml@eks-branch
    with:
      tag: ${{ needs.build.outputs.unique-tag }}
      namespace: ${{ needs.configure.outputs.namespace }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD_APP_DEPLOY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD_APP_DEPLOY }}

#  notify:
#    name: 'Notify'
#    if: ${{ always() }}
#    needs: [prepare, build, deploy]
#    uses: rfcx/cicd/.github/workflows/notify-send.yaml@master
#    with:
#      repo: device-api
#      branch-name: ${{ needs.prepare.outputs.branch-name }}
#      workflow-id: cd.yaml
#      previous-run-id: ${{ needs.prepare.outputs.previous-run-id }}
#      status: ${{ needs.deploy.result }}
#      always: true
#      notification-title: 'CD: Device API'
#      notification-footer: "Build: ${{ needs.build.result || 'n/a' }} | Deploy: ${{ needs.deploy.result || 'n/a' }}"
#      notification-success-statement: '{0} deployed the build!'
#    secrets:
#      slack-webhook: ${{ secrets.SLACK_ALERT_COREDT_WEBHOOK }}
#      github-token: ${{ secrets.GITHUB_TOKEN }}
